package main.dataBase;

public class Keywords
{
    private String name;
    private KeywordType type;

    public Keywords(String name, KeywordType type)
    {
        //todo name notNullNotBlank
        this.name = name;
        this.type = type;
    }

    public String getName()
    {
        return name;
    }

    public KeywordType getType()
    {
        return type;
    }

    public enum KeywordType{
        BILIRUBIN_IM_BLUT_DIREKT_ERNIEDRIGT,
        ULTRASCHALLGESTEUERTE_BRUSTBIOPSIE,
        SERUM_CROSSLAPS_ERHOET,
        BETA_CROSSLAPS,
        VOXEL_BASIERTES_SPEZIFISCHES_REGIONALES_ANALYSESYSTEM,
        MRT_SIGNALAENDERUNG_IM_GEHIRN,
        MRT_SIGNALAENDERUNG_IM_HIRNSTAMM,
        MRT_SINGALAENDERUNG_IM_KLEINHIRN,
        MRT_SIGNALAENDERUNG_IN_DENbASALGANGLIEN,
        MRT_SIGNALAENDERUNG_IM_THALAMUS,
        ERHOETER_IGF_1,
        ELEKTRORETINOGRAMM_A_WELLEN_AMPLITUDE_ERNIEDRIGT,
        ELEKTRORETINOGRAMM_B_WELLEN_AMPLITUDE_ERNIEDRIGT,
        CHROMOGENER_TEST_ZUR_FAKTOR_X_AKTIVITAETSBESTIUMMUNG_NORMAL,
        CHROMOGENER_TEST_ZURaNTI_FAKTOR_XA_BESTIMMUNG_NORMAL,
        FENO_NORMAL,
        FENO_ANORMAL,
        GASTRALE_RESIDUALVOLUMEN_HOCH,
        MAXILLOFAZIALER_CT_SCAN_NORMAL,
        MAXILLOFAZIALER_CT_SCAN,
        MAXILLOFAZIALER_CT_SCAN_ANORMAL,
        DE_RITIS_QOTIENT,
        NORMALBLASTENZAHL,
        GESCHAETZTE_GLOMERULAERE_FILTRATIONSRATE,
        GESCHAETZTE_GFR,
        ZYSTIN_INI_LEUKOZYTEN_ERHOEHT,
        COENZYM_Q_ERHOET,
        VIRUS_ABSTRICH,
        LYMPHKNOTEN_EXZISIONSBIOPSIE,
        NICHTINVASIVE_PRAENATALE_UNTERSUCHUNG,
        PRAENAATALES_ZELLFREIES_DNA_SCREENING,
        BIOPSIE_DES_OMENTUMS,
        HEUFT_ARTHROSKOIE,
        MUMFORD_VERFAHREN,
        GLAUKOMADRAINAGE_IMPLANTATION,
        GLAUKOM_DRAINAGEOPERATION,
        EPIGLOTTISLAPPENREKONSTRUKTION,
        DERMIS_FETT_TRANSPLANAT,
        BIOTIN_ERGAENZUNG,
        PANTOTHENSAEURE_ERGAENZUNG,
        MITTLERE_LUNGENLOBEKTOMIE,
        OBERE_LUNGENLOBEKTOMIE,
        LUNGENBILOBEKTOMIE,
        EXTRAPLEURALE_LUNGENBILBOBEKTOMIE,
        EXTRAPLEURALE_LUNGENLOBEKTOMIE,
        SLEEVE_LOBEKTOMIE,
        UNTERE_LUNGENLOBEKTOMIE,
        SLEEVE_PNEUMONEKTOMIE,
        INTRAVESIKALE_BCG_THERAPIE,
        ZAHNBRUECKENPLATZIERUNG,
        ASPIRATIONSTHEROMBEKTOMIE,
        IMPLANTIERBARE_LOOP_RECORDER,
        RADIOFREQUENZ_NEUROTOMIE,
        BURCH_VERFAHREN,
        FOKALE_ADIPOLYSE,
        INJEKTIONSLIPOLYSE,
        UNTERKINN_LIPOLYSE,
        INTERNE_REPARATUR_EINER_HERNIE,
        DEKOMPRESSION_DES_NERVUS_TRIGEMINUS,
        ELEKTROMAGNETISCHE_THERAPIE,
        ENDOMETRIOSE_KAUTERISIERUNG;
    }
}


